### ISSUE TITLE
1.7.7 breaks Typescript build with Angular 2.3

### ISSUE THREAD

**Issue by d-damien** [tb/ng2-nouislider#154]
When running our build script, the typescript line is :
``` ts
tsc -t es5 --moduleResolution node --emitDecoratorMetadata --sourceMap false --experimentalDecorators --module commonjs src/main.ts
```
Error message is :
```
node_modules/ng2-nouislider/src/nouislider.d.ts(1,55): error TS2305: Module '"[...]node_modules/@angular/core/index"' has no exported member 'Renderer2'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

Temporary solution is to install previous version :
``` bash
npm i ng2-nouislider@1.7.6
```

**Comment by d-damien** [comment]
Really old Angular version.
